buildNo_SUT_platform_content_master = "18"
buildTypePartialPath = "regular"
currentNoMonth = "10"
currentYear = "2016"
currentYearFolder = "2016 Folder"
currentMonthYear_controlGenerate = "October 2016"
currentMonthYear_updateGenerate = "October 2016"
updateGenerateVersionFolder = "1.101"
updateGenerateTypeFolder = "1.101.12.P"
orderPartialPath = "Functional" #{Prior, Regression}
updateTypePartialPath = "Regular" #{Regular, Backfill}
Status = "Update" #{Production, Update}
supplementalNo = "0" #DO NOT add first digit--assuming no more than 9 Supplementals
System = "Additional"
testType = "Functional" #{Functional, Regression}
CobolInfo = "//devsrv005/L/Cobol 410"
CInfo = "//devsrv005/L/C_408"
PLSQLInfo = "//devsrv005/L/taxtestutl"
currentPLSQLFolder = "//devsrv005/L/plsql410"
updateResultsFolder = "T:/WIL/Departments/TaxContentQA/Test Artifacts & Results/SUT Content Update"
templateFolder = "T:/WIL/Departments/TaxContentQA/Test Artifacts & Results/Special_Projects/SUT Automation/Template"
