VMname = "devsrv006"
buildNo_SUT_platform_content_master = "37"
buildTypePartialPath = "regular" #regular, supplemental, supplemental2
currentYear = "2016"
currentYearFolder = "2016 Folder"
currentMonthYear_controlGenerate = "October 2016"
currentMonthYear_updateGenerate = "October 2016"
updateGenerateVersionFolder = "1.101"
updateGenerateTypeFolder = "1.101.12.P"
System = "Additional"
CobolVersion = "Cobol_420"
CVersion = "C_408"
PLSQLVersion = "plsql410"
CobolInfo = "//"+VMname+"/L/"+CobolVersion
CInfo = "//"+VMname+"/L/"+CVersion
PLSQLInfo = "//"+VMname+"/L/taxtestutl"
currentPLSQLFolder = "//"+VMname+"/L/"+PLSQLVersion
currentNoMonth = "10"
orderPartialPath = "Prior"
updateGenerateFolder = "1.101/1.101.12.P"
updateTypePartialPath = "Regular"
