VMname = "devsrv005"
buildNo_SUT_platform_content_master = "37"
buildTypePartialPath = "supplemental1" #regular, supplemental, supplemental2
currentNoMonth = "10"
currentYear = "2016"
currentYearFolder = "2016 Folder"
currentMonthYear_controlGenerate = "October 2016"
currentMonthYear_updateGenerate = "October 2016"
updateGenerateVersionFolder = "1.101"
updateGenerateTypeFolder = "1.101.12.P"
orderPartialPath = "Prior" #{Prior, Functional, Regression}-think folders
updateTypePartialPath = "Regular" #{Regular, Backfill}
Status = "Production" #{Production, Update}-think status of testing
System = "Additional"
testType = "Regression" #{Functional, Regression}
CobolVersion = "Cobol_410"
CVersion = "C_408"
PLSQLVersion = "plsql410"
CobolInfo = "//"+VMname+"/L/"+CobolVersion
CInfo = "//"+VMname+"/L/"+CVersion
PLSQLInfo = "//"+VMname+"/L/taxtestutl"
currentPLSQLFolder = "//"+VMname+"/L/"+PLSQLVersion
