VMname = "devsrv005"
buildNo_SUT_platform_content_master = "34"
buildTypePartialPath = "regular" #regular, supplemental, supplemental2
currentNoMonth = "09"
currentYear = "2016"
currentYearFolder = "2016 Folder"
currentMonthYear_controlGenerate = "September 2016"
currentMonthYear_updateGenerate = "September 2016"
updateGenerateVersionFolder = "1.100"
updateGenerateTypeFolder = "1.100.2.P"
orderPartialPath = "Prior" #{Prior, Functional, Regression}-think folders
updateTypePartialPath = "Backfill" #{Regular, Backfill}
priorMonthYear = "July 2016"
Status = "Production" #{Production, Update}-think status of testing
System = "Additional"
testType = "Functional" #{Functional, Regression}
CobolVersion = "Cobol_410"
CVersion = "C_408"
PLSQLVersion = "plsql410"
CobolInfo = "//"+VMname+"/L/"+CobolVersion
CInfo = "//"+VMname+"/L/"+CVersion
PLSQLInfo = "//"+VMname+"/L/taxtestutl"
currentPLSQLFolder = "//"+VMname+"/L/"+PLSQLVersion
