buildNo_SUT_platform_content_master = "18"
buildTypePartialPath = "regular"
currentNoMonth = "06"
currentYear = "2016"
currentYearFolder = "2016 Folder"
currentMonthYear_controlGenerate = "June 2016"
currentMonthYear_updateGenerate = "July_2016"
updateGenerateVersionFolder = "1.95"
updateGenerateTypeFolder = "1.95.14.T"
orderPartialPath = "Prior" #{Prior, Regression}
updateTypePartialPath = "Regular" #{Regular, Backfill}
priorMonthYear = "March 2016"
Status = "Production" #{Production, Update}
supplementalNo = "00"
System = "Additional"
testType = "Functional" #{Functional, Regression}
CobolInfo = "//devsrv005/L/Cobol 410"
CInfo = "//devsrv005/L/C_407"
PLSQLInfo = "//devsrv005/L/taxtestutl"
currentPLSQLFolder = "//devsrv005/L/plsql403"
updateResultsFolder = "T:/WIL/Departments/TaxContentQA/Test Artifacts & Results/SUT Content Update"
templateFolder = "T:/WIL/Departments/TaxContentQA/Test Artifacts & Results/Special_Projects/SUT Automation/Template"